on: workflow_dispatch

name: Publish Crates.io CI

jobs:
    build_and_test:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release --all-features
            - name: test
              shell: bash
              run: cargo test
            - name: publish
              shell: bash
              run: cargo publish
              env:
                  CARGO_REGISTRY_TOKEN: "${{ secrets.CARGO_REGISTRY_TOKEN }}"
